services:
  - type: web
    name: chessed
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chessed-db
          property: connectionString

databases:
  - name: chessed-db
    plan: free
